---

- name: Prepare k3s cluster
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- name: Setup k3s servers
  hosts: master
  become: true
  roles:
    - role: k3s_server

- name: Setup k3s agents
  hosts: node
  become: true
  roles:
    - role: k3s_agent

- name: Configure k3s cluster
  hosts: master
  become: true
  roles:
    - role: k3s_server_post
